version: '2'
services:
  web:
     image: ncrawler/msa_stemmers:image: ncrawler/msa_stemmers:0.0.6-dev
     container_name: msa_stemmers__dev
     hostname: msa_stemmers__dev
     command: runserver
     volumes:
       - .:/application/msa_stemmers
     ports:
       - "17920:8000"
