version: '2'
services:
  web:
     image: docker.force.fm/msa/stemmers:latest
     container_name: msa_stemmers__dev
     hostname: msa_stemmers__dev
     command: runserver
     volumes:
       - .:/application/msa_stemmers
     ports:
       - "17920:8000"
