version: '2.1'
services:
  py36-base:
    image: stemmers:latest-alpine
    command: na
    environment:
      GUNICORN_MODULE: gunicorn_release
      UWSGI_HARAKIRI: 10
      PYTHONUNBUFFERED: 1
    sysctls:
#      - fs.file-max=150000
#      - kernel.pid_max=4194303
#      - net.ipv4.ip_local_port_range=1024 65535
#      - kernel.sched_migration_cost_ns=5000000
#      - kernel.sched_autogroup_enabled=0
#      - net.ipv4.tcp_slow_start_after_idle=0
#      - net.ipv4.tcp_no_metrics_save=0
#      - net.ipv4.tcp_abort_on_overflow=0
      - net.ipv4.tcp_window_scaling=1
#      - net.ipv4.tcp_tw_recycle=1
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_syncookies=1
      - net.ipv4.tcp_syn_retries=2
      - net.ipv4.tcp_synack_retries=2
      - net.ipv4.tcp_orphan_retries=2
      - net.ipv4.tcp_retries2=8
#      - net.core.netdev_max_backlog=3240000
      - net.core.somaxconn=50000
      - net.ipv4.tcp_max_tw_buckets=1440000
      - net.ipv4.tcp_max_syn_backlog=3240000
#      - net.core.rmem_default=16777216
#      - net.core.wmem_default=16777216
#      - net.core.optmem_max=16777216
#      - net.core.rmem_max=16777216
#      - net.core.wmem_max=16777216
#      - net.ipv4.tcp_mem=16777216 16777216 16777216
#      - net.ipv4.tcp_wmem=4096 87380 16777216
#      - net.ipv4.tcp_rmem=4096 87380 16777216
      - net.ipv4.tcp_keepalive_time=600
      - net.ipv4.tcp_keepalive_intvl=10
      - net.ipv4.tcp_keepalive_probes=9
      - net.ipv4.tcp_fin_timeout=7
      - net.ipv4.tcp_sack=0
#      - net.ipv4.tcp_dsack=0
#      - net.ipv4.tcp_fack=0
      - net.ipv4.tcp_timestamps=0

  py36-uwsgi:
    extends: py36-base
    command: uwsgi
    environment:
      UWSGI_WORKERS: 1
      UWSGI_CHEAPER: 0
    ports:
      - "8000:8000"

#  py36-gunicorn:
#    extends: py36-base
#    command: gunicorn
#    ports:
#      - "17930:8000"
#
#  py36-bjoern:
#    extends: py36-base
#    command: bjoern
#    ports:
#      - "17932:8000"
#
  # ===========
#  pypy35-base:
#    image: stemmers:latest-pypy
#    command: na
#    environment:
#      GUNICORN_MODULE: gunicorn_release
#      UWSGI_HARAKIRI: 10
#      PYTHONUNBUFFERED: 1
#
#  pypy35-bjoern:
#    extends: pypy35-base
#    command: bjoern
#    ports:
#      - "18920:8000"
#
#  pypy35-gunicorn:
#    extends: pypy35-base
#    command: gunicorn
#    ports:
#      - "18921:8000"
#
#  pypy35-uwsgi:
#    extends: pypy35-base
#    command: uwsgi
#    environment:
#      UWSGI_PYPY_HOME: /usr/local
#      UWSGI_PYPY_LIB: /usr/local/bin/libpypy3-c.so
#    ports:
#      - "18922:8000"





































